# PostgreSQL. Versions 8.2 and up are supported.
development:
  adapter: postgresql
  encoding: unicode
  database: truestack_development
  pool: 5
  username: truestack
  password: truestack

test:
  adapter: postgresql
  encoding: unicode
  database: truestack_test
  pool: 5
  username: truestack
  password: truestack

production:
  adapter: postgresql
  encoding: unicode
  database: truestack_production
  pool: 5
  username: truestack
  password: wenotuseapassword
